// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: fdnconfig.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fdnconfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Separator   *Separator             `protobuf:"bytes,1,opt,name=Separator,proto3" json:"Separator,omitempty"`
	ToSepWords  []*ToSepWord           `protobuf:"bytes,6,rep,name=ToSepWords,proto3" json:"ToSepWords,omitempty"`
	TermWords   []*TermWord            `protobuf:"bytes,7,rep,name=TermWords,proto3" json:"TermWords,omitempty"`
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=LastUpdated,proto3" json:"LastUpdated,omitempty"`
}

func (x *Fdnconfig) Reset() {
	*x = Fdnconfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fdnconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fdnconfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fdnconfig) ProtoMessage() {}

func (x *Fdnconfig) ProtoReflect() protoreflect.Message {
	mi := &file_fdnconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fdnconfig.ProtoReflect.Descriptor instead.
func (*Fdnconfig) Descriptor() ([]byte, []int) {
	return file_fdnconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Fdnconfig) GetSeparator() *Separator {
	if x != nil {
		return x.Separator
	}
	return nil
}

func (x *Fdnconfig) GetToSepWords() []*ToSepWord {
	if x != nil {
		return x.ToSepWords
	}
	return nil
}

func (x *Fdnconfig) GetTermWords() []*TermWord {
	if x != nil {
		return x.TermWords
	}
	return nil
}

func (x *Fdnconfig) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type TermWord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyHash       string `protobuf:"bytes,1,opt,name=KeyHash,proto3" json:"KeyHash,omitempty"`
	OriginalLower string `protobuf:"bytes,2,opt,name=OriginalLower,proto3" json:"OriginalLower,omitempty"`
	TargetWord    string `protobuf:"bytes,3,opt,name=TargetWord,proto3" json:"TargetWord,omitempty"`
}

func (x *TermWord) Reset() {
	*x = TermWord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fdnconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TermWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermWord) ProtoMessage() {}

func (x *TermWord) ProtoReflect() protoreflect.Message {
	mi := &file_fdnconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermWord.ProtoReflect.Descriptor instead.
func (*TermWord) Descriptor() ([]byte, []int) {
	return file_fdnconfig_proto_rawDescGZIP(), []int{1}
}

func (x *TermWord) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *TermWord) GetOriginalLower() string {
	if x != nil {
		return x.OriginalLower
	}
	return ""
}

func (x *TermWord) GetTargetWord() string {
	if x != nil {
		return x.TargetWord
	}
	return ""
}

type ToSepWord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyHash string `protobuf:"bytes,1,opt,name=KeyHash,proto3" json:"KeyHash,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *ToSepWord) Reset() {
	*x = ToSepWord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fdnconfig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToSepWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToSepWord) ProtoMessage() {}

func (x *ToSepWord) ProtoReflect() protoreflect.Message {
	mi := &file_fdnconfig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToSepWord.ProtoReflect.Descriptor instead.
func (*ToSepWord) Descriptor() ([]byte, []int) {
	return file_fdnconfig_proto_rawDescGZIP(), []int{2}
}

func (x *ToSepWord) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *ToSepWord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Separator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyHash string `protobuf:"bytes,1,opt,name=KeyHash,proto3" json:"KeyHash,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Separator) Reset() {
	*x = Separator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fdnconfig_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Separator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Separator) ProtoMessage() {}

func (x *Separator) ProtoReflect() protoreflect.Message {
	mi := &file_fdnconfig_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Separator.ProtoReflect.Descriptor instead.
func (*Separator) Descriptor() ([]byte, []int) {
	return file_fdnconfig_proto_rawDescGZIP(), []int{3}
}

func (x *Separator) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *Separator) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_fdnconfig_proto protoreflect.FileDescriptor

var file_fdnconfig_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x64, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x09, 0x66, 0x64, 0x6e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2d, 0x0a, 0x09, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x53, 0x65, 0x70, 0x61,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x0a, 0x54, 0x6f, 0x53, 0x65, 0x70, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x54, 0x6f, 0x53, 0x65, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x54, 0x6f, 0x53, 0x65,
	0x70, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x09, 0x54, 0x65, 0x72, 0x6d, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x54, 0x65, 0x72, 0x6d, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x09, 0x54, 0x65, 0x72, 0x6d, 0x57,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x22, 0x6a, 0x0a, 0x08, 0x54, 0x65, 0x72, 0x6d, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x4b, 0x65, 0x79, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4b, 0x65, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x22, 0x3b,
	0x0a, 0x09, 0x54, 0x6f, 0x53, 0x65, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4b,
	0x65, 0x79, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4b, 0x65,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x53,
	0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4b, 0x65, 0x79, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fdnconfig_proto_rawDescOnce sync.Once
	file_fdnconfig_proto_rawDescData = file_fdnconfig_proto_rawDesc
)

func file_fdnconfig_proto_rawDescGZIP() []byte {
	file_fdnconfig_proto_rawDescOnce.Do(func() {
		file_fdnconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_fdnconfig_proto_rawDescData)
	})
	return file_fdnconfig_proto_rawDescData
}

var file_fdnconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fdnconfig_proto_goTypes = []interface{}{
	(*Fdnconfig)(nil),             // 0: main.fdnconfig
	(*TermWord)(nil),              // 1: main.TermWord
	(*ToSepWord)(nil),             // 2: main.ToSepWord
	(*Separator)(nil),             // 3: main.Separator
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_fdnconfig_proto_depIdxs = []int32{
	3, // 0: main.fdnconfig.Separator:type_name -> main.Separator
	2, // 1: main.fdnconfig.ToSepWords:type_name -> main.ToSepWord
	1, // 2: main.fdnconfig.TermWords:type_name -> main.TermWord
	4, // 3: main.fdnconfig.LastUpdated:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_fdnconfig_proto_init() }
func file_fdnconfig_proto_init() {
	if File_fdnconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fdnconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fdnconfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fdnconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TermWord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fdnconfig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToSepWord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fdnconfig_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Separator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fdnconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fdnconfig_proto_goTypes,
		DependencyIndexes: file_fdnconfig_proto_depIdxs,
		MessageInfos:      file_fdnconfig_proto_msgTypes,
	}.Build()
	File_fdnconfig_proto = out.File
	file_fdnconfig_proto_rawDesc = nil
	file_fdnconfig_proto_goTypes = nil
	file_fdnconfig_proto_depIdxs = nil
}
