// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: fdnrecord.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fdnrecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records     []*Record              `protobuf:"bytes,6,rep,name=Records,proto3" json:"Records,omitempty"`
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=LastUpdated,proto3" json:"LastUpdated,omitempty"`
}

func (x *Fdnrecord) Reset() {
	*x = Fdnrecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fdnrecord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fdnrecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fdnrecord) ProtoMessage() {}

func (x *Fdnrecord) ProtoReflect() protoreflect.Message {
	mi := &file_fdnrecord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fdnrecord.ProtoReflect.Descriptor instead.
func (*Fdnrecord) Descriptor() ([]byte, []int) {
	return file_fdnrecord_proto_rawDescGZIP(), []int{0}
}

func (x *Fdnrecord) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Fdnrecord) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviousName string                 `protobuf:"bytes,2,opt,name=PreviousName,proto3" json:"PreviousName,omitempty"`
	CurrentName  string                 `protobuf:"bytes,3,opt,name=CurrentName,proto3" json:"CurrentName,omitempty"`
	LastUpdated  *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=LastUpdated,proto3" json:"LastUpdated,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fdnrecord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_fdnrecord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_fdnrecord_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetPreviousName() string {
	if x != nil {
		return x.PreviousName
	}
	return ""
}

func (x *Record) GetCurrentName() string {
	if x != nil {
		return x.CurrentName
	}
	return ""
}

func (x *Record) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_fdnrecord_proto protoreflect.FileDescriptor

var file_fdnrecord_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x64, 0x6e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x09, 0x66, 0x64, 0x6e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x3c, 0x0a,
	0x0b, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b,
	0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0b,
	0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x4c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fdnrecord_proto_rawDescOnce sync.Once
	file_fdnrecord_proto_rawDescData = file_fdnrecord_proto_rawDesc
)

func file_fdnrecord_proto_rawDescGZIP() []byte {
	file_fdnrecord_proto_rawDescOnce.Do(func() {
		file_fdnrecord_proto_rawDescData = protoimpl.X.CompressGZIP(file_fdnrecord_proto_rawDescData)
	})
	return file_fdnrecord_proto_rawDescData
}

var file_fdnrecord_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fdnrecord_proto_goTypes = []interface{}{
	(*Fdnrecord)(nil),             // 0: main.fdnrecord
	(*Record)(nil),                // 1: main.Record
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_fdnrecord_proto_depIdxs = []int32{
	1, // 0: main.fdnrecord.Records:type_name -> main.Record
	2, // 1: main.fdnrecord.LastUpdated:type_name -> google.protobuf.Timestamp
	2, // 2: main.Record.LastUpdated:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fdnrecord_proto_init() }
func file_fdnrecord_proto_init() {
	if File_fdnrecord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fdnrecord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fdnrecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fdnrecord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fdnrecord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fdnrecord_proto_goTypes,
		DependencyIndexes: file_fdnrecord_proto_depIdxs,
		MessageInfos:      file_fdnrecord_proto_msgTypes,
	}.Build()
	File_fdnrecord_proto = out.File
	file_fdnrecord_proto_rawDesc = nil
	file_fdnrecord_proto_goTypes = nil
	file_fdnrecord_proto_depIdxs = nil
}
